services:
  app:
    build:
      args:
        - DEV=true
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             uvicorn app.asgi:application --host 0.0.0.0 --port 8000 --reload"
    environment:
      - DEBUG=True
