jobs:
  deploy:
    runs-on: self-hosted
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    defaults:
      run:
        working-directory: /home/ubuntu/actions-runner/_work/docnet_backend/docnet_backend

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up environment
      run: |
        echo "${{ secrets.ENV_FILE }}" > .env
        chmod 600 .env

    - name: Build and start Docker containers
      run: make up

    - name: Run Django migrations
      run: make docker-migrate

    - name: Restart services
      run: make restart

    - name: Restart Nginx
      run: sudo service nginx restart
